use data_report;
CREATE TABLE company(
    ID 	VARCHAR(32) PRIMARY KEY NOT NULL COMMENT '公司唯一编号',
    NAME VARCHAR(128) NOT NULL COMMENT '公司名称',
    type VARCHAR(16) COMMENT '公司类型',
    grade VARCHAR(16) COMMENT '公司级别',
    STATUS VARCHAR(16) DEFAULT 'T' NOT NULL COMMENT '公司状态',
    CITY VARCHAR(16) COMMENT '城市',
    ADDRESS VARCHAR(128) COMMENT '详细地址',
    PHONE VARCHAR(128) COMMENT '电话',
    EMAIL VARCHAR(128) COMMENT '邮箱',
    NOTE TEXT COMMENT '备注',
    ATTR TEXT COMMENT '公司的属性，布局、样式、logo、等JSON数据'
);

CREATE TABLE role(
    ID VARCHAR(32) PRIMARY KEY NOT NULL COMMENT '角色唯一编号',
    NAME VARCHAR(128) NOT NULL COMMENT '角色名称——系统管理员，公司管理员，空间管理员，普通用户',
    STATUS VARCHAR(16) DEFAULT 'T' NOT NULL COMMENT '角色状态',
    NOTE TEXT COMMENT '备注',
    ATTR TEXT COMMENT '角色的属性，布局、样式、logo、等JSON数据'
);

CREATE TABLE groups(
    ID VARCHAR(32) PRIMARY KEY NOT NULL COMMENT '组编号',
    NAME VARCHAR(128) NOT NULL COMMENT '组名称——公开空间，测试空间，其他空间',
    NOTE TEXT COMMENT '备注',
    ATTR TEXT COMMENT '组的属性，布局、样式、logo、等JSON数据'
);

CREATE TABLE users(
    ID VARCHAR(32) PRIMARY KEY NOT NULL COMMENT '用户唯一编号',
    NAME VARCHAR(128) NOT NULL COMMENT '用户姓名',
    PWD VARCHAR(128) NOT NULL COMMENT '用户密码',
    STATUS VARCHAR(16) DEFAULT 'T' NOT NULL COMMENT '用户状态',
    PHONE VARCHAR(128) COMMENT '电话',
    EMAIL VARCHAR(128) COMMENT '邮箱',
    SPACE_ID VARCHAR(32) COMMENT '空间唯一编号',
    COMPANY_ID VARCHAR(32) NOT NULL COMMENT '公司唯一编号',
    ROLE_ID VARCHAR(32) DEFAULT '0' NOT NULL COMMENT '角色唯一编号',
    NOTE TEXT COMMENT '备注',
    ATTR TEXT COMMENT '用户的属性，布局、样式、logo、等JSON数据',
    LOGIN_IP VARCHAR(20)  COMMENT '登录IP',
    LOGIN_TIME VARCHAR(20) COMMENT '登录时间',
    CONSTRAINT user_company_ibfk_1 FOREIGN KEY (COMPANY_ID) REFERENCES company (ID),
    CONSTRAINT user_role_ibfk_3 FOREIGN KEY (ROLE_ID) REFERENCES role (ID)
);

CREATE TABLE space(
	ID VARCHAR(32) PRIMARY KEY NOT NULL COMMENT '空间唯一编号',
    NAME VARCHAR(128) NOT NULL COMMENT '空间名称',
    STATUS VARCHAR(16) DEFAULT 'T' NOT NULL COMMENT '空间状态',
    COMPANY_ID VARCHAR(32) NOT NULL COMMENT '公司唯一编号',
    GROUP_ID VARCHAR(32) NOT NULL COMMENT '空间组编号',
    USER_ID VARCHAR(32) NOT NULL COMMENT '创建人ID',
    CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
    NOTE TEXT COMMENT '备注',
    ATTR TEXT COMMENT '空间的属性，布局、样式、logo、等JSON数据',
    CONSTRAINT space_company_ibfk_3 FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID),
    CONSTRAINT space_group_ibfk_3 FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (ID),
    CONSTRAINT space_users_ibfk_3 FOREIGN KEY (USER_ID) REFERENCES users (ID)
);
CREATE INDEX FK_GROUP_ID ON space (GROUP_ID);
CREATE INDEX FK_COMPANY_ID ON space (COMPANY_ID);


CREATE TABLE report(
    ID VARCHAR(32) PRIMARY KEY NOT NULL COMMENT '报表编号',
    NAME VARCHAR(128) NOT NULL COMMENT '报表名称',
    PUB VARCHAR(16) DEFAULT 'F' NOT NULL COMMENT '报表是否向普通用户公开',
    TOKEN VARCHAR(128) COMMENT '报表公开访问TOKEN',
    STATUS VARCHAR(16) DEFAULT 'T' NOT NULL COMMENT '报表状态',
    COMPANY_ID VARCHAR(32) NOT NULL COMMENT '公司唯一编号',
    SPACE_ID VARCHAR(32) NOT NULL COMMENT '空间唯一编号',
    USER_ID VARCHAR(32) NOT NULL COMMENT '创建人ID',
    CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
    NOTE TEXT COMMENT '备注',
    ATTR TEXT COMMENT '报表页面的属性，布局、样式、logo、等JSON数据',
    CONSTRAINT report_company_ibfk_1 FOREIGN KEY (COMPANY_ID) REFERENCES company (ID),
    CONSTRAINT report_space_ibfk_2 FOREIGN KEY (SPACE_ID) REFERENCES space (ID),
    CONSTRAINT report_users_ibfk_3 FOREIGN KEY (USER_ID) REFERENCES users (ID)
);
CREATE INDEX FK_REPORT_SPACE_ID ON report (SPACE_ID);
CREATE UNIQUE INDEX UK_REPORT_NAME ON report (NAME);


CREATE TABLE dashboard(
    ID VARCHAR(32) PRIMARY KEY NOT NULL COMMENT '大屏编号',
    NAME VARCHAR(128) NOT NULL COMMENT '大屏名称',
    PUB VARCHAR(16) DEFAULT 'F' NOT NULL COMMENT '大屏是否向普通用户公开',
    TOKEN VARCHAR(128) COMMENT '大屏公开访问TOKEN',
    STATUS VARCHAR(16) DEFAULT 'T' NOT NULL COMMENT '大屏状态',
    COMPANY_ID VARCHAR(32) NOT NULL COMMENT '公司唯一编号',
    SPACE_ID VARCHAR(32) NOT NULL COMMENT '空间唯一编号',
    USER_ID VARCHAR(32) NOT NULL COMMENT '创建人ID',
    CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
    NOTE TEXT COMMENT '备注',
    ATTR TEXT COMMENT '大屏页面的属性，布局、样式、logo、等JSON数据',
    CONSTRAINT dashboard_company_ibfk_1 FOREIGN KEY (COMPANY_ID) REFERENCES company (ID),
    CONSTRAINT dashboard_space_ibfk_2 FOREIGN KEY (SPACE_ID) REFERENCES space (ID),
    CONSTRAINT dashboard_users_ibfk_3 FOREIGN KEY (USER_ID) REFERENCES users (ID)
);
CREATE INDEX FK_DASH_SPACE_ID ON report (SPACE_ID);
CREATE UNIQUE INDEX UK_DASH_NAME ON report (NAME);


CREATE TABLE resource(
    ID VARCHAR(32) PRIMARY KEY NOT NULL COMMENT '数据源编号',
    NAME VARCHAR(128) NOT NULL COMMENT '数据源名称',
    URL VARCHAR(128) NOT NULL COMMENT '数据源URL',
    PUB VARCHAR(16) DEFAULT 'F' NOT NULL COMMENT '数据源是否公开给普通用户使用',
    TOKEN VARCHAR(128) COMMENT '数据源TOKEN',
    STATUS VARCHAR(16) DEFAULT 'T' NOT NULL COMMENT '数据源状态',
    COMPANY_ID VARCHAR(32) NOT NULL COMMENT '公司唯一编号',
    SPACE_ID VARCHAR(32) NOT NULL COMMENT '空间唯一编号',
    USER_ID VARCHAR(32) NOT NULL COMMENT '创建人ID',
    CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
    NOTE TEXT COMMENT '备注',
    ATTR TEXT COMMENT '数据源的属性，布局、样式、logo、等JSON数据',
    CONSTRAINT resource_company_ibfk_1 FOREIGN KEY (COMPANY_ID) REFERENCES company (ID),
    CONSTRAINT resource_space_ibfk_2 FOREIGN KEY (SPACE_ID) REFERENCES space (ID),
    CONSTRAINT resource_users_ibfk_3 FOREIGN KEY (USER_ID) REFERENCES users (ID)
);
CREATE INDEX FK_RESOURCE_SPACE_ID ON resource (SPACE_ID);
CREATE INDEX FK_RESOURCE_COMPANY_ID ON resource (COMPANY_ID);